name: 'phpDoc Checker'
description: 'GitHub Action for Tests YetiForceCRM - phpDoc Checker'
branding:
  icon: 'check-square'
  color: 'blue'

runs:
  using: "composite"
  steps:
    - run: ./checker.sh
      shell: bash