name: 'YetiForceCRM Tests Action - MariaDB'
description: 'Debian 11 | PHP 7.4 | MariaDB'
branding:
  icon: 'check-square'
  color: 'blue'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ matrix.vdb }}
    - ${{ env.dbxxxx }}
    